from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid


class MonetizationSettings(models.Model):
    """Global monetization feature toggle and configuration"""
    is_enabled = models.BooleanField(default=False, help_text="Enable/disable monetization feature")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=1000.00, help_text="Price in Naira")
    payment_account = models.CharField(
        max_length=255,
        default="Osimi Godsgift Gbubemi 7049946769 Opay",
        help_text="Payment account details to display"
    )
    whatsapp_number = models.CharField(
        max_length=20,
        default="07049946769",
        help_text="WhatsApp number for receipt submission"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Monetization Settings"
        verbose_name_plural = "Monetization Settings"

    def __str__(self):
        return f"Monetization Settings ({'Enabled' if self.is_enabled else 'Disabled'})"


class ActivationCode(models.Model):
    """Activation codes generated by admin for users to unlock features"""
    code = models.CharField(max_length=50, unique=True, help_text="Unique activation code")
    is_used = models.BooleanField(default=False, help_text="Whether code has been used")
    used_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, help_text="User who used this code")
    created_at = models.DateTimeField(auto_now_add=True)
    used_at = models.DateTimeField(null=True, blank=True, help_text="When the code was used")

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.code} ({'Used' if self.is_used else 'Unused'})"


class UserActivation(models.Model):
    """Track user feature activation status"""
    STATUS_CHOICES = [
        ('locked', 'Locked'),
        ('unlocked', 'Unlocked'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='activation_status')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='locked')
    activation_code = models.ForeignKey(ActivationCode, on_delete=models.SET_NULL, null=True, blank=True)
    activated_at = models.DateTimeField(null=True, blank=True, help_text="When user activated their account")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User Activation"
        verbose_name_plural = "User Activations"

    def __str__(self):
        return f"{self.user.username} - {self.status}"

    def unlock(self, activation_code):
        """Unlock user with activation code"""
        self.status = 'unlocked'
        self.activation_code = activation_code
        self.activated_at = timezone.now()
        self.save()
