# Generated by Django 5.1.6 on 2025-06-01 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_testsession_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptest',
            name='scheduled_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
