# Generated by Django 5.1.6 on 2025-06-14 13:33

import django.db.models.deletion
import exams.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_material_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='gcs_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(storage=exams.storage_backends.GoogleCloudMediaStorage(), upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
