# Generated by Django 5.1.6 on 2025-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_material_gcs_url_alter_material_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='gcs_url',
        ),
    ]
