# Generated by Django 5.1.6 on 2025-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_question_source_file_question_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
