# Generated by Django 5.1.6 on 2025-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(default='2019', max_length=255),
        ),
    ]
